package com.edupass.biometric.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RectangleShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.ExitToApp
import androidx.compose.material.icons.filled.Lock
import androidx.compose.material.icons.filled.QrCode
import androidx.compose.material.icons.filled.School
import androidx.compose.material3.Divider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.RectangleShape
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.edupass.biometric.ui.components.BrutalistButton
import com.edupass.biometric.ui.components.BrutalistCard
import com.edupass.biometric.ui.components.ServerStatusCard
import com.edupass.biometric.ui.theme.AccentGreen
import com.edupass.biometric.ui.theme.CrispWhite
import com.edupass.biometric.ui.theme.MutedText
import com.edupass.biometric.ui.theme.PitchBlack
import com.edupass.biometric.ui.theme.SafetyOrange
import com.edupass.biometric.ui.theme.StudioGrey
import com.edupass.biometric.ui.viewmodel.AuthViewModel

@Composable
fun StudentDashboardScreen(
    viewModel: AuthViewModel,
    onLogout: () -> Unit
) {
    val state by viewModel.uiState.collectAsState()
    val scrollState = rememberScrollState()
    var isProofGenerated by remember { mutableStateOf(false) }
    var simulatedHash by remember { mutableStateOf("") }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(StudioGrey)
            .verticalScroll(scrollState)
    ) {
        // TOP APP BAR
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .background(CrispWhite)
                .border(2.dp, PitchBlack)
                .padding(horizontal = 16.dp, vertical = 10.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Icon(Icons.Default.School, contentDescription = null, tint = PitchBlack)
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = "STUDENT PASSPORT PORTAL",
                    fontFamily = FontFamily.Monospace,
                    fontWeight = FontWeight.Black,
                    fontSize = 13.sp,
                    color = PitchBlack
                )
            }
            IconButton(onClick = onLogout) {
                Icon(Icons.Default.ExitToApp, contentDescription = "Logout", tint = PitchBlack)
            }
        }

        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp)
        ) {
            // DIGITAL PRIVACY PASSPORT CARD
            BrutalistCard(
                backgroundColor = PitchBlack,
                shadowOffset = 6.dp
            ) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = "DIGITAL PRIVACY PASSPORT",
                        fontFamily = FontFamily.Monospace,
                        fontWeight = FontWeight.Bold,
                        fontSize = 11.sp,
                        color = SafetyOrange
                    )
                    Box(
                        modifier = Modifier
                            .background(AccentGreen)
                            .padding(horizontal = 6.dp, vertical = 2.dp)
                    ) {
                        Text(
                            text = "BIOMETRIC ANCHOR ACTIVE",
                            fontFamily = FontFamily.Monospace,
                            fontWeight = FontWeight.Bold,
                            fontSize = 8.sp,
                            color = PitchBlack
                        )
                    }
                }

                Spacer(modifier = Modifier.height(8.dp))

                Text(
                    text = "STUDENT ID: ${state.userId}",
                    fontFamily = FontFamily.Monospace,
                    fontWeight = FontWeight.Black,
                    fontSize = 18.sp,
                    color = CrispWhite
                )

                Text(
                    text = "HOLDER: RAMESH KUMAR // B.SC COMPUTER SCIENCE",
                    fontFamily = FontFamily.SansSerif,
                    fontSize = 12.sp,
                    color = CrispWhite.copy(alpha = 0.8f)
                )

                Spacer(modifier = Modifier.height(12.dp))
                Divider(color = SafetyOrange, thickness = 1.dp)
                Spacer(modifier = Modifier.height(8.dp))

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Text("ZK CIRCUIT: CIRCOM-2.1", fontFamily = FontFamily.Monospace, fontSize = 9.sp, color = CrispWhite)
                    Text("STATUS: ZERO LEAKAGE", fontFamily = FontFamily.Monospace, fontSize = 9.sp, color = AccentGreen)
                }
            }

            Spacer(modifier = Modifier.height(20.dp))

            // EMBEDDED REMOTE HTTP BIOMETRIC TRIGGER SERVER CARD
            ServerStatusCard(
                deviceIp = state.deviceIpAddress,
                port = 8080,
                isServerRunning = state.isServerRunning,
                onToggleServer = { viewModel.toggleServer() },
                onTestTrigger = { viewModel.simulateTestTrigger() },
                recentLog = state.latestServerLog
            )

            Spacer(modifier = Modifier.height(20.dp))

            // VERIFIABLE CREDENTIALS LIST
            Text(
                text = "[01] MY VERIFIABLE CREDENTIALS:",
                fontFamily = FontFamily.Monospace,
                fontWeight = FontWeight.Bold,
                fontSize = 12.sp,
                color = PitchBlack
            )

            Spacer(modifier = Modifier.height(8.dp))

            val credentials = listOf(
                Pair("BACHELOR OF SCIENCE (CS)", "MIT UNIVERSITY • ISSUED MAY 2026"),
                Pair("ACADEMIC TRANSCRIPT (ENCRYPTED)", "VERIFIABLE GPA & MARKSHEET SEAL"),
                Pair("AI BIOMETRIC PASSPORT ANCHOR", "FINGERPRINT & FACE PROOF BOUND")
            )

            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(CrispWhite)
                    .border(2.dp, PitchBlack)
            ) {
                credentials.forEachIndexed { idx, item ->
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(14.dp),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Column(modifier = Modifier.weight(1f)) {
                            Text(
                                text = item.first,
                                fontFamily = FontFamily.SansSerif,
                                fontWeight = FontWeight.Black,
                                fontSize = 13.sp,
                                color = PitchBlack
                            )
                            Text(
                                text = item.second,
                                fontFamily = FontFamily.Monospace,
                                fontSize = 10.sp,
                                color = MutedText
                            )
                        }
                        Icon(Icons.Default.CheckCircle, contentDescription = null, tint = AccentGreen)
                    }
                    if (idx < credentials.size - 1) {
                        Divider(color = PitchBlack, thickness = 1.dp)
                    }
                }
            }

            Spacer(modifier = Modifier.height(20.dp))

            // ZK-PROOF GENERATOR INTERACTIVE SIMULATOR
            Text(
                text = "[02] GENERATE ZERO-KNOWLEDGE PROOF:",
                fontFamily = FontFamily.Monospace,
                fontWeight = FontWeight.Bold,
                fontSize = 12.sp,
                color = PitchBlack
            )

            Spacer(modifier = Modifier.height(8.dp))

            BrutalistCard(
                backgroundColor = SafetyOrange,
                shadowOffset = 4.dp
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Icon(Icons.Default.Lock, contentDescription = null, tint = PitchBlack)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = "PRIVACY PROOF GENERATOR",
                        fontFamily = FontFamily.SansSerif,
                        fontWeight = FontWeight.Black,
                        fontSize = 16.sp,
                        color = PitchBlack
                    )
                }

                Spacer(modifier = Modifier.height(6.dp))

                Text(
                    text = "Generate a cryptographic proof that your GPA > 3.5 and Degree is Authentic WITHOUT revealing your actual grades or raw transcript document.",
                    fontFamily = FontFamily.SansSerif,
                    fontSize = 11.sp,
                    color = PitchBlack
                )

                Spacer(modifier = Modifier.height(14.dp))

                BrutalistButton(
                    text = if (isProofGenerated) "RE-GENERATE ZK PROOF" else "GENERATE ZK PROOF NOW",
                    tag = "CIRCOM",
                    backgroundColor = PitchBlack,
                    contentColor = SafetyOrange,
                    onClick = {
                        isProofGenerated = true
                        simulatedHash = "0x" + (1..32).map { "0123456789ABCDEF".random() }.joinToString("")
                    }
                )

                if (isProofGenerated) {
                    Spacer(modifier = Modifier.height(14.dp))
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .background(CrispWhite)
                            .border(2.dp, PitchBlack)
                            .padding(12.dp)
                    ) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween
                        ) {
                            Text("ZK PROOF CREATED:", fontFamily = FontFamily.Monospace, fontWeight = FontWeight.Bold, fontSize = 10.sp, color = PitchBlack)
                            Text("VERIFIED", fontFamily = FontFamily.Monospace, fontWeight = FontWeight.Bold, fontSize = 10.sp, color = AccentGreen)
                        }
                        Spacer(modifier = Modifier.height(4.dp))
                        Text(
                            text = simulatedHash,
                            fontFamily = FontFamily.Monospace,
                            fontSize = 10.sp,
                            color = PitchBlack
                        )
                        Spacer(modifier = Modifier.height(6.dp))
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.QrCode, contentDescription = null, tint = PitchBlack)
                            Spacer(modifier = Modifier.width(4.dp))
                            Text("READY TO PRESENT TO EMPLOYERS / VERIFIERS", fontFamily = FontFamily.Monospace, fontSize = 9.sp, color = MutedText)
                        }
                    }
                }
            }
        }
    }
}
